version: 2.1

jobs:
  test:
    docker: 
      - image: circleci/golang:buster
    steps:
      - checkout
      - run:
          name: Running tests
          command: |
            cd ~/project/auth-by-email
            go test -v -coverprofile=coverage.out
            go tool cover -html=coverage.out -o ~/project/coverage.html
      - store_artifacts:
          path: ~/project/coverage.html
  build:
    docker: 
      - image: circleci/golang:buster
    steps:
      - checkout
      - run:
          name: Compiling caddy
          command: |
            cd ~/project/caddy
            go build
            ~/project/caddy/caddy -plugins | grep authbyemail
      - run:
          name: Compiling usermod
          command: |
            cd ~/project/usermod
            go build
      - run:
          name: Compiling migrate
          command: |
            cd ~/project/migrate
            go build
      - store_artifacts:
          path: ~/project/caddy/caddy
          destination: caddy
      - store_artifacts:
          path: ~/project/usermod/usermod
          destination: usermod
      - store_artifacts:
          path: ~/project/migrate/migrate
          destination: migrate

workflows:
  version: 2
  test-build:
    jobs:
      - test:
          filters:
            branches:
              only:
                - master
      - build:
          requires:
            - test
          filters:
            branches:
              only:
                - master
